on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  frontend:
    runs-on: ubuntu-latest
    name: Install and Build Frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install and build
        working-directory: frontend
        run: |
          npm install
          npm run build
          npm run test -- --watch=false --browsers=ChromeHeadless
          npx cypress run --headless
 #       continue-on-error: true  # Omitimos error de mongodb por incompatibilidad de versiones 
                                   # BSONArray::bsonSerialize(), 
                                   # https://www.mongodb.com/community/forums/t/php-mongodb-2-0-0-bsonarray-bsonserialize-error-bsonarray-php-on-line-74/318628/4

  backend:
    runs-on: ubuntu-latest
    name: Install and Test Backend
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup PHP with MongoDB
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mongodb-1.21.0, zip
          tools: composer:v2
           
      
      - name: Verify MongoDB extension
        run: php -m | grep mongodb
      
      - name: Install Composer dependencies
        working-directory: backend
        run:  composer install --no-interaction --prefer-dist --ignore-platform-req=ext-mongodb
    
      
      - name: Setup Laravel environment
        working-directory: backend
        run: |
          cp .env.example .env
          php artisan key:generate
      
      - name: Run tests
        working-directory: backend
        run: php artisan test
 #       continue-on-error: true  #Omitimos error de mongodb por incompatibilidad de versiones 
                                   # BSONArray::bsonSerialize(), 
                                   # https://www.mongodb.com/community/forums/t/php-mongodb-2-0-0-bsonarray-bsonserialize-error-bsonarray-php-on-line-74/318628/4
       
