on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  frontend:
    runs-on: ubuntu-latest
    name: Install and Build Frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: |
          cd frontend 
          npm install
          npm run build
          npm run test -- --watch=false --browsers=ChromeHeadless
          npx cypress run --headless

  backend:
    runs-on: ubuntu-latest
    name: Install and Test Backend
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mongodb, zip 
     
       - run: |
          cd backend 
          composer install
          cp .env.example .env
          php artisan key:generate
          php artisan test
