on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  frontend:
    runs-on: ubuntu-latest
    name: Install and Build Frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: |
          ls -R
          cd frontend && npm install
          cd frontend && npm run build
          cd frontend && npm test
          cd frontend && npm run cypress:run

  backend:
    runs-on: ubuntu-latest
    name: Install and Test Backend
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - run: |
          cd backend && composer install
          cd backend && cp .env.example .env
          cd backend && php artisan key:generate
          cd backend && php artisan test
